### ISSUE TITLE
Find a better way to position form errors on login.html

### ISSUE THREAD

**Issue by kurealnum** [kurealnum/non-profit-link#14]
Errors render with no errors, but they're a tad bit sideways. See this image:
![image](https://github.com/kurealnum/non-profit-link/assets/116363763/b4b1d5cb-8a5f-42a0-8596-e845ca496440)

**Comment by kurealnum** [comment]
My apologies for the indescriptive issue. Let me attach another file for comparison.
![image](https://github.com/kurealnum/non-profit-link/assets/116363763/698ba9ce-1821-4fc7-923c-d215b59d7cac)

This is how I'd like errors on the login page to display, directly above the input element, not the label element.

**Comment by vyshnav-vinod** [comment]
I would love to work on this issue
