### ISSUE TITLE
Change logout view to use Django's built in logout view

### ISSUE THREAD

**Issue by kurealnum** [kurealnum/non-profit-link#20]
When I first implemented the logout_user view in accounts/, I didn't realize that Django already had a view for this. I need someone to remove the logout_user view from accounts/views.py, and update any occurrences of logout user accordingly. There should be only one occurrence, that being in layout.html. There might be more though, so please check everything.

Docs: https://docs.djangoproject.com/en/5.0/topics/auth/default/#django.contrib.auth.views.LogoutView

**Comment by 0aaryan** [comment]
hey, I would like to work on it.Can you assign it to me?
